# Welcome to Numpy tutorial

In [1]:
import numpy as np

In [2]:
myarr=np.array([[1,2,3,4],[9,8,7,5] ])

In [3]:
myarr[1,2]+myarr[1,3]

12

In [4]:
myarr.shape

(2, 4)

In [5]:
myarr.dtype

dtype('int32')

In [6]:
myarr[0,1]=45

In [7]:
myarr

array([[ 1, 45,  3,  4],
       [ 9,  8,  7,  5]])

# Array Creation : Conversion from other Python structures (e.g., lists, tuples)

In [8]:
listarray=np.array([[1,2,3,4],[5,6,7,8]])

In [9]:
listarray

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
listarray.size


8

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.shape


(2, 4)

In [13]:
np.array(({43,43,23}))

array({43, 23}, dtype=object)

# Array creation: Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)

In [14]:
zeroes=np.zeros((2,5))

In [15]:
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
zeroes.dtype

dtype('float64')

In [17]:
zeroes.shape

(2, 5)

In [18]:
rng=np.arange(10)

In [19]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
lspace=np.linspace(5,4,12)

In [21]:
lspace


array([5.        , 4.90909091, 4.81818182, 4.72727273, 4.63636364,
       4.54545455, 4.45454545, 4.36363636, 4.27272727, 4.18181818,
       4.09090909, 4.        ])

In [22]:
lspace=np.linspace(5,50,10)

In [23]:
lspace

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [24]:
emp=np.empty((4,6))

In [25]:
emp

array([[1.27839897e-311, 5.41495948e-321, 0.00000000e+000,
        1.19563886e-321, 1.27839897e-311, 5.41990013e-321],
       [0.00000000e+000, 1.19563886e-321, 1.27839897e-311,
        5.42484079e-321, 0.00000000e+000, 1.19563886e-321],
       [1.27839897e-311, 5.44460342e-321, 0.00000000e+000,
        1.19563886e-321, 1.27839897e-311, 5.43966276e-321],
       [0.00000000e+000, 1.19563886e-321, 1.27839897e-311,
        5.42978145e-321, 0.00000000e+000, 1.19563886e-321]])

In [26]:
emp_like=np.empty_like(lspace)

In [27]:
emp_like

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [28]:
ide=np.identity((3))

In [29]:
ide


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
arr=np.arange((99))

In [31]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
arr.reshape((3,33))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [33]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [34]:
arr=arr.reshape((3,33))

In [35]:
arr


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [36]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [37]:
arr.shape

(3, 33)

In [38]:
arr.shape

(3, 33)

In [39]:
arr=arr.ravel()

In [40]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [41]:
arr.shape

(99,)

In [42]:
arr=[[1,2,3],[4,5,6]]

In [43]:
arr


[[1, 2, 3], [4, 5, 6]]

In [44]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [45]:
arr=np.array(x)

In [46]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
arr.sum(axis=0)

array([12, 15, 18])

In [48]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [49]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [50]:
arr.flat

In [51]:
for item in arr.flat:
 print(item)

1
2
3
4
5
6
7
8
9


In [52]:
arr.ndim


2

In [53]:
arr.size

9

In [54]:
arr.nbytes


36

In [55]:
one=np.array([1,4,678,45,2])

In [56]:
one.argsort()

array([0, 4, 1, 3, 2], dtype=int64)

In [57]:
one.argmin()

0

In [58]:
one.argmax()

2

In [59]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [60]:
arr.argmin()

0

In [61]:
arr.argmax()

8

In [62]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [63]:
arr.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [64]:
arr.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [65]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [67]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [68]:
arr.sum()

45

In [69]:
np.where(arr>4)

(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))

In [70]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
np.where(arr>4)

(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))

In [72]:
arr.dtype

dtype('int32')

In [73]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [74]:
arr=np.array(x)

In [75]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
np.where(arr>7)

(array([2, 2], dtype=int64), array([1, 2], dtype=int64))

In [77]:
np.where(arr>4)

(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))

In [78]:
np.count_nonzero(arr)

9

In [79]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [80]:
arr[1,2]=0

In [81]:
import sys

In [82]:
py_arr=[[1,2,3]]

In [83]:
nm_py=np.array(py_arr)

In [84]:
sys.getsizeof(1) * len(py_arr)

28

In [85]:
nm_py.itemsize * nm_py.size

12

In [86]:
nm_py.tolist()

[[1, 2, 3]]

In [87]:
myarr=np.array([1,2,3],np.int64)

In [88]:
myarr

array([1, 2, 3], dtype=int64)

In [89]:
myarr.dtype

dtype('int64')

In [93]:
myarr=np.zeros(0)

In [94]:
myarr

array([], dtype=float64)